install:
	python3 install.py --name APICapture

install-builder:
	python3 install.py --name APICapture_Build --mode build

close-set:
	pkill -x "Ableton Live 12 Suite"

open-set:
	open ./set/set.als

reload:
	just install-builder && just close-set && sleep 1 && just open-set

pipeline *args:
	python3 run_pipeline.py {{args}}

watch:
	python3 watch.py
