import inspect
import sys
import os

from ..helpers.app import get_version_number
from .Generator import Generator


class DocumentationGenerator(Generator):
    lines = []

    def __init__(self, module, outdir, script_dir):
        header = f"""
        <?xml-stylesheet type="text/css" href="../Live.css"?>
        <Root>
            <Live>
            <Header>Live API Version {get_version_number(module)}</Header>
            <Doc>
                Running Python version {sys.version.split(' ')[0]}
            </Doc>
            <Doc>
                Unofficial Live API documentation generated by the "API_MakeDoc" MIDI Remote Script.
                This is unofficial documentation. Please do not contact Ableton with questions or problems relating to the use of this documentation
            </Doc>
        """

        footer = """
            </Live>
        </Root>
        """

        super().__init__(
            module,
            outdir,
            script_dir,
            os.path.join(outdir, str(module.__name__) + ".xml"),
            header,
            footer,
        )

    def _get_doc(self, obj):
        """Get object's doc string and remove \n's and clean up <'s and >'s for XML compatibility"""

        if getattr(obj, "__doc__") is not None:
            return self._clean_doc(getattr(obj, "__doc__"))

    def _clean_doc(self, doc):
        """Remove \n's and clean up <'s and >'s for XML compatibility"""

        doc = doc.replace(
            "\n", ""
        )  # remove newlines from Live API docstings, for wrapped display
        doc = doc.replace(
            "   ", ""
        )  # Strip chunks of whitespace from docstrings, for wrapped display
        doc = doc.replace("&", "&amp;")
        doc = doc.replace("<", "&lt;")  # replace XML reserved characters
        doc = doc.replace(">", "&gt;")
        return doc

    def _print_obj_info(self, description, obj, name=None):
        """Print object's descriptor and name on one line, and docstring (if any) on the next"""

        # Safely retrieve __name__ if it exists
        obj_name = getattr(obj, "__name__", None)
        recovered_doc = None

        # Boost.Python sometimes concatenates the docstring onto __name__;
        # strip the overlap by checking if __doc__ text appears as a suffix
        if obj_name:
            obj_doc = getattr(obj, "__doc__", None) or ""
            if obj_doc and len(obj_name) > len(obj_doc):
                overlap = obj_name[len(obj_name) - len(obj_doc):]
                if obj_doc.startswith(overlap):
                    obj_name = obj_name[:len(obj_name) - len(obj_doc)]
            # If name had a space and __doc__ is None, Boost.Python concatenated the
            # doc directly into __name__. Split at the last CamelCase boundary
            # (lowercase followed by uppercase) to recover the real class name.
            if " " in obj_name:
                first_word = obj_name.split(" ", 1)[0]
                rest = obj_name[len(first_word):].strip()
                if not obj_doc:
                    for i in range(len(first_word) - 1, 0, -1):
                        if first_word[i - 1].islower() and first_word[i].isupper():
                            rest = first_word[i:] + " " + rest if rest else first_word[i:]
                            first_word = first_word[:i]
                            break
                    if rest:
                        recovered_doc = rest.rstrip(".")
                obj_name = first_word

        # Filter out unnamed Boost.Python functions and special methods
        if obj_name:
            if "<" in obj_name or obj_name.startswith("__"):
                return

        # Determine the name to use
        name_str = obj_name if obj_name is not None else name

        # Proceed only if name_str is available
        if name_str is None:
            self.write(f"Warning: No name available for object {obj}. Skipping.")
            return

        # Handle self.lines stack
        if len(self.lines) != 0:
            assert name_str is not None

            self.lines.append("." + name_str)
            if inspect.ismethod(obj) or inspect.isbuiltin(obj):
                self.lines[-1] += "()"
        else:
            self.lines.append(name_str)

        # Build the line string
        line_str = "".join(self.lines)

        # Print the formatted description
        self.write(
            "<%s>%s<Description>%s</Description></%s>\n"
            % (description, line_str, description, description)
        )

        # Print the docstring if available
        if hasattr(obj, "__doc__") and getattr(obj, "__doc__"):
            self.write(f"<Doc>\t{self._get_doc(obj)}</Doc>\n")
        elif recovered_doc:
            self.write(f"<Doc>\t{self._clean_doc(recovered_doc)}</Doc>\n")
