// @ts-check
// vibe-coded: substantial AI-assisted authoring. Review before relying on.
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";

// https://astro.build/config
export default defineConfig({
  site: "https://photonicvelocity.github.io",
  base: "/LiveAPI",
  integrations: [
    starlight({
      title: "LiveAPI",
      description:
        "Reference for the Ableton Live Object Model (LOM) — types, behavior, and quirks.",
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/PhotonicVelocity/LiveAPI",
        },
      ],
      sidebar: [
        // Root index.mdx (splash hero page) is reachable via the site
        // title at the top of the sidebar; no separate "Overview" entry
        // needed.
        //
        // Foundation pages are hoisted above the alphabetical Modules
        // list — they describe cross-cutting models (LOM, Remote
        // Scripts) that every per-class reference page assumes. Each
        // also still appears in the autogenerated Modules group below
        // (same URL, two paths to land on it) unless flagged
        // `sidebar_hidden:` in its lom YAML.
        //
        // The "Live Object Model" group nests LomObject's identity /
        // lifetime page alongside the LOM's two cross-cutting
        // mechanics — Listeners (subscription model) and Calling
        // conventions (positional-only signatures). Remote scripts
        // sits separately because it describes Live's runtime
        // execution model (how Live loads the script, the tick, the
        // threading rules), not the LOM itself.
        {
          label: "Remote scripts",
          link: "/remote-scripts/",
          badge: { text: "core", variant: "tip" },
        },
        {
          label: "Live Object Model",
          badge: { text: "core", variant: "tip" },
          collapsed: false,
          items: [
            { label: "Overview", link: "/live-object-model/" },
            { label: "Listeners", link: "/listeners/" },
            {
              label: "Calling conventions",
              link: "/calling-conventions/",
            },
            {
              label: "Modules",
              autogenerate: { directory: "modules" },
              collapsed: false,
            },
          ],
        },
      ],
      // Right-side TOC down to member level (H3) — Sphinx/Blender style.
      // Members and sections both show up; the page content is its own
      // navigation surface.
      tableOfContents: { minHeadingLevel: 2, maxHeadingLevel: 3 },
      customCss: ["./src/styles/custom.css"],
      // Footer override appends an "independent reference, not affiliated
      // with Ableton" disclaimer below Starlight's default footer content
      // on every page.
      components: {
        Footer: "./src/components/Footer.astro",
      },
    }),
  ],
});
