// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";

// https://astro.build/config
export default defineConfig({
  site: "https://photonicvelocity.github.io",
  base: "/LiveAPI",
  integrations: [
    starlight({
      title: "LiveAPI",
      description:
        "Reference for the Ableton Live Object Model (LOM) — types, behavior, and quirks.",
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/PhotonicVelocity/LiveAPI",
        },
      ],
      sidebar: [
        // Root index.mdx (splash hero page) is reachable via the site
        // title at the top of the sidebar; no separate "Overview" entry
        // needed.
        //
        // LomObject is hoisted above the alphabetical Modules list as a
        // first-class entry — it's the foundation page describing the
        // universal identity / lifetime / construction model that every
        // other LOM class inherits, and the [LomObject] badge in class
        // signatures across the site links to it. Keeping it inline with
        // the alphabetical list (between "Listener" and "LooperDevice")
        // would bury it. The page still appears in the autogenerated
        // Modules group below — same URL, two paths to land on it.
        {
          label: "LomObject",
          link: "/modules/lomobject/",
          badge: { text: "core", variant: "tip" },
        },
        {
          label: "Listener",
          link: "/modules/listener/",
          badge: { text: "core", variant: "tip" },
        },
        {
          label: "Modules",
          autogenerate: { directory: "modules" },
          collapsed: false,
        },
      ],
      // Right-side TOC down to member level (H3) — Sphinx/Blender style.
      // Members and sections both show up; the page content is its own
      // navigation surface.
      tableOfContents: { minHeadingLevel: 2, maxHeadingLevel: 3 },
      customCss: ["./src/styles/custom.css"],
    }),
  ],
});
